### PR TITLE
fixed main entry in package.json

### PR DESCRIPTION
**Pull request by svashish305**
@anbugal @anthonywebb @shadowbrush Merging this should close issue #46

### CODE REVIEW

**Comment by pikiaboy** [comment]
@nsoni3 @jekh, Please merge this in ASAP; No one is able to import the SDK since the main entry is not correctly defined.

**Comment by pikiaboy** [comment]
As its been over a week and I still no activity, there is a solution for those looking to patch this manually. 

https://www.npmjs.com/package/patch-package

You can use this to apply the patch yourself to get you up and running.

**Comment by jekh** [comment]
@pikiaboy The fix for this has already been merged, but it hasn't been published to npm. Merging this PR would actually re-break it.

#46 should be closed for the same reason.

**Comment by svashish305** [comment]
> > @pikiaboy The fix for this has already been merged, but it hasn't been published to npm. Merging this PR would actually re-break it.
> > #46 should be closed for the same reason.
> 
> @jekh in that case can you publish the latest changes on npm so that I can retest and close the pr accordingly.

I am able to work with my apis using latest released version 3, closing this PR, thanks everyone for fixing this

**Pull request closed without merging**
